# config.yaml

# List of ticker symbols to collect
tickers:
  - AAPL
  - GOOGL
  - MSFT

# Date range for price collection
start_date: "2014-01-01"
end_date: "today"    # We can interpret "today" in Python code

# Interval for price data (1d, 1wk, 1mo, etc.)
interval: "1d"

# Local paths for data
local_paths:
  raw_data: "data/raw"
  processed_data: "data/processed"

# s3 utils

s3_bucket: "financialdata-sa"
s3_folders_paths:
  raw_news: "RawNews/"

